MyTest/Models/Book.cs
namespace MyTest.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public decimal Cost { get; set; }
    }
}

MyTest/Models/ErrorViewModel.cs
namespace MyTest.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyTest/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyTest.Models;
using System.Diagnostics;

namespace MyTest.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyTest/Controllers/MyController.cs
using Microsoft.AspNetCore.Mvc;
using MyTest.Models;
using System.Data.SqlClient;
using Dapper;
using System.Data;

namespace MyTest.Controllers
{
    public class MyController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            //ViewData["key1"] = "hello";
            //ViewData["key2"] = "STEP";

            //ViewData["key3"] = new Book
            //{
            //    Id = 1,
            //    Title="Война и мир",
            //    Cost = 1000
            //};

            //var model = new List<Book>()
            //{
            //    new Book{Id = 1,Title = "Война и мир", Cost = 1000 },
            //    new Book{Id = 2,Title = "Евгений Онегин", Cost = 2000 }
            //};

            //ViewData["key4"] = model;

            //using (SqlConnection db = new SqlConnection(""))
            {
                //var book = db.Query<Book>("select id, title, cost from book where id = 1").FirstOrDefault();
                //return View(book);
                return View(new Book
                {
                    Id = 10,
                    Title = "Война и мир 2",
                    Cost = 10000
                });
            }
        }

        [HttpPost]
        public ActionResult Index(Book model)
        {
            //using (SqlConnection db = new SqlConnection(""))
            {
                //DynamicParameters p = new DynamicParameters(model);
                //var result = db.ExecuteScalar<string>("pBook", p, commandType: CommandType.StoredProcedure);
                var result = "exists";
                if (result == "exists")
                {
                    ModelState.AddModelError("", "This book already exists");
                    return View();
                }
                return Redirect("");
            }
        }
    }
}

MyTest/Views/My/Index.cshtml
@*@model IEnumerable<Book>;*@

@model Book;

@using MyTest.Models;
@using System.Collections

@*<h2>@ViewData["key1"]
@ViewData["key2"]</h2>

@{
    var book = @ViewData["key3"] as Book;
    var id = book.Id;
    var cost = book.Cost;
    var title = book.Title;
}

@{
    var books = ViewData["key4"] as IEnumerable<Book>;

    foreach (Book item in books)
    {
        @Html.Raw("<li>" + item.Id + " " +item.Title + "</li>");
    }
}

@{
    foreach (Book item in Model)
    {
        @Html.Raw("<li>" + item.Id + " " +item.Title + "</li>");
    }
}*@

@*<h2>@id</h2>
<h2>@title</h2>
<h2>@cost</h2>*@

@using (Html.BeginForm("Index", "My", FormMethod.Post))
{
    @Html.ValidationSummary();
    @Html.TextBoxFor(m => m.Id, new { @class = "form-control" });
    <br />
    @Html.TextBoxFor(m => m.Title, new { @class = "form-control" });
    <br />
    @Html.TextBoxFor(m => m.Cost, new { @class = "form-control" });

    <input type="submit" value="Send"/>
}

MyTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyTest</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyTest.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyTest</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MyTest - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>